networks:
  pdfnet:

volumes:
  postgres-data:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - pdfnet

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - pdfnet

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pdfdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pdfnet

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./data/incoming:/data/incoming
      - ./data/processed:/data/processed
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - postgres
    networks:
      - pdfnet
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DATABASE_URL: postgresql://user:password@postgres:5432/pdfdb

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres
    networks:
      - pdfnet
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DATABASE_URL: postgresql://user:password@postgres:5432/pdfdb

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres
    networks:
      - pdfnet
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DATABASE_URL: postgresql://user:password@postgres:5432/pdfdb
    